[tool.coverage.run]
source = ["authapp", "tasks"]
omit = ["*/migrations/*", "*/tests/*", "*/__init__.py", "manage.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "def __str__",
    "if self.debug"
]
precision = 2
fail_under = 80
